version: '3.3'

services:
  mysql:
    image: mysql:9.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: reservations_mederi
    volumes:
      - ./mysql_data:/var/lib/mysql/

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: 'root'
      DB_PASSWORD: '1234'
      DB_HOST: 'mysql'
      DB_NAME: 'reservations_mederi'
      DB_PORT: '3306'
      JWT_SECRET: 'CFQU6P0kJu7TWztmioayBRZv9cXMwGH5'
      EMAIL_PASSWORD: 'vohwxkbondmfygdp'
      EMAIL_ACCOUNT: 'mensajesprueba45@gmail.com'
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      PMA_HOST: mysql
    ports:
      - "8080:80"
